"""empty message

Revision ID: 6ae1c42ab336
Revises: 9cb8e10c0349
Create Date: 2022-05-22 12:58:20.324715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae1c42ab336'
down_revision = '9cb8e10c0349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testing_migrate')
    op.add_column('puzzle', sa.Column('date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'date')
    op.create_table('testing_migrate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('test_one', sa.INTEGER(), nullable=True),
    sa.Column('test_two', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
